---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    default_users: [rossedman]
    default_packages: [curl, git, wget, vim, cockpit, cockpit-docker]
    docker_group_members: [rossedman]
  roles:
    - angstwad.docker_ubuntu
  tasks:
    # install sane defaults
    - apt: "name={{ item }} state=installed update_cache=yes"
      loop: "{{ default_packages }}"
    
    # user creation
    - user:
        name: "{{ item }}"
        groups:
          - sudo
        state: present
      loop: "{{ default_users }}"

    - file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        mode: 0700
      loop: "{{ default_users }}"

    - get_url:
        url: "https://github.com/{{item}}.keys"
        dest: "/home/{{item}}/.ssh/authorized_keys"
        mode: 0600
      loop: "{{ default_users }}"
