apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    role: monitoring
    tier: database
    app: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: monitoring
        tier: database
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.5.4
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        env:
        - name: INFLUXDB_DB
          value: "influxdb"
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "false"
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: influxdb