---
- name: remove old docker packages
  become: true
  apt: 
    name: "{{ item }}" 
    state: absent
  loop:
    - docker 
    - docker-engine 
    - docker.io

- name: add docker repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: add docker repo key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker
  become: true
  apt: 
    name: "docker-ce=17.03.3~ce-0~ubuntu-xenial"
    update_cache: yes
    autoremove: yes
    force: yes

- name: create docker group
  become: true
  group: 
    name: docker 
    state: present

- name: add users to docker group
  become: true
  user: 
    name: "{{ item }}"
    groups: docker 
    append: yes
  loop: "{{ docker_users }}"

- name: start docker
  service: 
    name: docker 
    enabled: yes 
    state: started
  